name: Sik-Kim
author: Jeong Sik Kim
url : "https://sik-kim.github.io"
baseurl: ""
description:  techblog
github: https://github.com/Sik-Kim
# twitter: http://www.twitter.com/
# facebook: http://www.facebook.com
# linkedin: http://www.linkedin.com
email: summering6@gmail.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
